name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Prepare .env
        run: cp .env.example .env
        shell: bash

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Types
        run: yarn check-types

      - name: Test
        run: yarn test:coverage

      - name: e2e
        run: yarn cypress:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          directory: combined-coverage

      - name: Build
        run: yarn build
